package scala.scalanative
package interflow

import scala.collection.mutable

import scala.scalanative.linker._
import scala.scalanative.nir.Defn.Define.DebugInfo
import scala.scalanative.util.ScopedVar.scopedPushIf

private[interflow] trait Opt { self: Interflow =>

  def shallOpt(name: nir.Global.Member): Boolean = {
    val defn =
      getOriginal(originalName(name))

    // With per-instruction try/catch (Opt.perInstructionTryCatch) methods
    // with unwind handlers are optimised too (see Eval.run / splitAtUnwind).
    defn.attrs.opt != nir.Attr.NoOpt &&
    (Opt.perInstructionTryCatch || !defn.hasUnwind)
  }

  /** While the body being optimised is an `@exported` wrapper (an extern
   *  definition generated by the compiler plugin, which boxes its C arguments
   *  and calls the Scala method once): the inlining depth of that body, else
   *  -1. See Inline.shallInline (`isExportTarget`).
   */
  private[interflow] val optimizingExportDepth: ThreadLocal[Int] =
    ThreadLocal.withInitial(() => -1)

  def opt(name: nir.Global.Member): nir.Defn.Define = {
    val previous = optimizingExportDepth.get
    optimizingExportDepth.set(
      if (Opt.inlineExportTargets &&
          getOriginal(originalName(name)).attrs.isExtern)
        inliningBacktrace.size
      else -1
    )
    try optBody(name)
    finally optimizingExportDepth.set(previous)
  }

  private def optBody(name: nir.Global.Member): nir.Defn.Define =
    in(s"visit ${name.show}") {
      val orig = originalName(name)
      val origtys = argumentTypes(orig)
      val origdefn = getOriginal(orig)
      val argtys = argumentTypes(name)
      val nir.Inst.Label(_, origargs) = origdefn.insts.head: @unchecked
      implicit val pos = origdefn.pos
      // Wrap up the result.
      def result(
          retty: nir.Type,
          rawInsts: Seq[nir.Inst],
          debugInfo: DebugInfo
      ) = {
        val insts = nir.ControlFlow.removeDeadBlocks(rawInsts)
        val newDebugInfo = if (preserveDebugInfo) {
          // TODO: filter-out unreachable scopes
          val scopes = debugInfo.lexicalScopes.sorted
          debugInfo.copy(lexicalScopes = scopes)
        } else debugInfo
        origdefn.copy(
          name = name,
          attrs = origdefn.attrs.withOpt(nir.Attr.DidOpt),
          ty = nir.Type.Function(argtys, retty),
          insts = insts,
          debugInfo = newDebugInfo
        )(origdefn.pos)
      }

      // Create new fresh and state for the first basic block.
      val fresh = nir.Fresh(0)
      val state = new State(nir.Local(0))(preserveDebugInfo)

      // Interflow usually infers better types on our erased type system
      // than scalac, yet we live it as a benefit of the doubt and make sure
      // that if original return type is more specific, we keep it as is.
      val nir.Type.Function(_, origRetTy) = origdefn.ty

      // Compute opaque fresh locals for the arguments. Argument types
      // are always a subtype of the original declared type, but in
      // some cases they might not be obviously related, despite
      // having the same concrete allocated class inhabitants.
      val args = argtys.zip(origtys).zip(origargs).map {
        case ((argty, origty), origarg) =>
          val ty = if (!Sub.is(argty, origty)) {
            log(
              s"using original argument type ${origty.show} instead of ${argty.show}"
            )
            origty
          } else argty

          val id = fresh()
          if (preserveDebugInfo) {
            origdefn.debugInfo.localNames
              .get(origarg.id)
              .foreach(state.localNames.update(id, _))
          }
          nir.Val.Local(id, ty)
      }

      // If any of the argument types is nothing, this method
      // is never going to be called, so we don't have to visit it.
      if (args.exists(_.ty == nir.Type.Nothing)) {
        val insts = Seq(
          nir.Inst.Label(nir.Local(0), args),
          nir.Inst.Unreachable(nir.Next.None)
        )
        result(nir.Type.Nothing, insts, DebugInfo.empty)
      } else
        scopedPushIf(preserveDebugInfo)(
          Seq(
            currentFreshScope := nir.Fresh(0L),
            currentLexicalScopes := mutable.UnrolledBuffer.empty
          )
        ) {
          // Run a merge processor starting from the entry basic block.
          val blocks =
            try {
              pushBlockFresh(fresh)
              process(
                origdefn.insts.toArray,
                debugInfo = origdefn.debugInfo,
                args = args,
                state = state,
                doInline = false,
                retTy = origRetTy,
                parentScopeId = nir.ScopeId.TopLevel
              )
            } finally {
              popBlockFresh()
            }

          // Collect instructions, materialize all returned values
          // and compute the result type.
          val insts = blocks.flatMap { block =>
            block.cf = block.cf match {
              case inst @ nir.Inst.Ret(retv) =>
                nir.Inst.Ret(block.end.materialize(retv))(inst.pos)
              case inst @ nir.Inst.Throw(excv, unwind) =>
                nir.Inst.Throw(block.end.materialize(excv), unwind)(inst.pos)
              case cf =>
                cf
            }
            block.toInsts()
          }
          val debugInfo: DebugInfo = if (preserveDebugInfo) {
            val localNames = mutable.OpenHashMap.empty[nir.Local, nir.LocalName]
            for {
              block <- blocks
              state = block.end
            } {
              localNames.addMissing(block.end.localNames)
            }
            DebugInfo(
              localNames = localNames.toMap,
              lexicalScopes = currentLexicalScopes.get.toSeq
            )
          } else DebugInfo.empty

          val rets = insts.collect {
            case nir.Inst.Ret(v) => v.ty
          }

          val retty0 = rets match {
            case Seq()   => nir.Type.Nothing
            case Seq(ty) => ty
            case tys     => Sub.lub(tys, Some(origRetTy))
          }
          // Make sure to not override expected BoxedUnit with primitive Unit
          val retty =
            if (retty0 == nir.Type.Unit && origRetTy.isInstanceOf[nir.Type.Ref])
              origRetTy
            else retty0

          result(retty, insts, debugInfo)
        }
    }

  def process(
      insts: Array[nir.Inst],
      debugInfo: DebugInfo,
      args: Seq[nir.Val],
      state: State,
      doInline: Boolean,
      retTy: nir.Type,
      parentScopeId: nir.ScopeId
  ): Seq[MergeBlock] = {
    val processor =
      MergeProcessor.fromEntry(
        insts =
          if (Opt.perInstructionTryCatch) Opt.splitAtUnwind(insts) else insts,
        args = args,
        debugInfo = debugInfo,
        state = state,
        doInline = doInline,
        blockFresh = blockFresh,
        eval = this,
        parentScopeId = parentScopeId
      )

    try {
      pushMergeProcessor(processor)

      while (!processor.done()) {
        processor.advance()
      }
    } finally {
      popMergeProcessor()
    }

    val blocks = processor.toSeq(retTy)
    MergePostProcessor.postProcess(blocks)
  }
}

private[interflow] object Opt {

  /** Optimise methods containing try/catch per instruction instead of
   *  leaving them unoptimised (see Eval.run, splitAtUnwind, inlineUnderTry).
   *  On by default since 0.5.12-gba4opt (the stage-2 codegen crash was
   *  Lower.genThrow's handler shortcut); disable with
   *  `-Dscalanative.interflow.perInstructionTryCatch=false`.
   */
  lazy val perInstructionTryCatch: Boolean =
    sys.props.get("scalanative.interflow.perInstructionTryCatch").forall(_.toBoolean)

  /** Escape the whole state before every instruction that may unwind (the
   *  original per-instruction try/catch rule) instead of only the values the
   *  handler can observe. `-Dscalanative.interflow.tryEscapeAll=true`.
   */
  lazy val tryEscapeAll: Boolean =
    sys.props.get("scalanative.interflow.tryEscapeAll").exists(_.toBoolean)

  /** Inline at call sites inside a try block, and callees that contain one
   *  (only with per-instruction try/catch). The inlined instructions unwind
   *  to the call site's handler (Eval.run `attachUnwind`). Disable with
   *  `-Dscalanative.interflow.inlineUnderTry=false`.
   */
  lazy val inlineUnderTry: Boolean =
    perInstructionTryCatch &&
      sys.props.get("scalanative.interflow.inlineUnderTry").forall(_.toBoolean)

  /** Inline the Scala method an `@exported` wrapper calls regardless of its
   *  size (its arguments are boxes the wrapper just made; inlined, they are
   *  scalar-replaced). `-Dscalanative.interflow.inlineExportTargets=false`
   *  disables it.
   */
  lazy val inlineExportTargets: Boolean =
    sys.props.get("scalanative.interflow.inlineExportTargets").forall(_.toBoolean)

  /** Ends the basic block after every instruction that has an unwind handler
   *  (by jumping to a fresh label), so that a block has at most one
   *  exceptional successor and the state at its end is the state on that
   *  edge. See Eval.run and MergeProcessor.updateDirectSuccessors.
   */
  def splitAtUnwind(insts: Array[nir.Inst]): Array[nir.Inst] = {
    val hasUnwind = insts.exists {
      case nir.Inst.Let(_, _, unwind) => unwind ne nir.Next.None
      case _                          => false
    }
    if (!hasUnwind) insts
    else {
      val fresh = nir.Fresh(insts.toSeq)
      val buf = mutable.UnrolledBuffer.empty[nir.Inst]
      insts.foreach {
        case let @ nir.Inst.Let(_, _, unwind) if unwind ne nir.Next.None =>
          implicit val pos: nir.SourcePosition = let.pos
          val cont = fresh()
          buf += let
          buf += nir.Inst.Jump(nir.Next.Label(cont, Nil))
          buf += nir.Inst.Label(cont, Nil)
        case inst =>
          buf += inst
      }
      buf.toArray
    }
  }
}
